### ISSUE TITLE
Update validate-settings script - remove mran repository test

### ISSUE THREAD

**Issue by jan-abel-inwt** [INWTlab/r-docker#34]
The mentioned script checks if a .`Rprofile` file exists. If it does, the script looks for a `mran` string in the `CRAN` named repository source and halts the execution if this string is not present. However, we switched from mran to the posit mirror last year, so this test needs to be updated or deleted. Do you have any advice on this, @wahani?

**Comment by miraKlein** [comment]
As discussed with @wahani, we can just remove this row.
I can do it, but I may need @jan-abel-inwt's help to deploy the new version of the containers.
